
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:4.0.0
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      
      - DEBUG=1
      - PERSISTENCE=1
      - LOCALSTACK_PERSISTENCE=1
      - SKIP_SSL_CERT_DOWNLOAD=1
      - LS_LOG=trace
      - SERVICES=s3,sqs,sns,apigateway
      - DOCKER_SOCK=/var/run/docker.sock
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTENSION_AUTO_INSTALL=localstack-extension-terraform-init
    volumes:
      - localstackData:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    
    networks:
      - front
      - back
      

volumes:
  localstackData:
networks:
  front:
  back:
